### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [mje-nz/zsh-themes#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by mje-nz** [comment]
Done, thank you for your interest!

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/818, thanks!
